# Generated by Django 3.1.3 on 2020-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='image/abc.jpg', upload_to='images'),
        ),
    ]
