# Generated by Django 3.1.3 on 2020-12-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
